### ISSUE TITLE
script not working with 55PUS7181/12

### ISSUE THREAD

**Issue by Aitchk4n** [suborb/philips_android_tv#19]
I run a homebridge on a pi 3 and have a 55 PUS from 2016...

when I m running the python script from Mac terminal I got always following error msg :

XXXX-MBP:TV XXX$ python philips.py --host 192.xxxx pair
Traceback (most recent call last):
  File "philips.py", line 6, in <module>

XXXX-MBP:TV XXX$ python philips.py --host 192.xxxx pair
Traceback (most recent call last):
  File "philips.py", line 8, in <module>
    from Crypto.Hash import SHA, HMAC
ImportError: No module named Crypto.Hash

Can someone help out? It would be so great to get this login details...some how:)

thx

**Comment by Aitchk4n** [comment]
solved it using on raspberry following commands upfront:

sudo apt-get install python-crypto
sudo apt-get install python-requests

afterwards the script worked fine.

**Comment by JeffersonBe** [comment]
I also solve this issue by running the following command:

`pip3 install -r requirements.txt `
