### ISSUE TITLE
Max retries exceeded with url: /6/pair/request  - Pairing 50PUS6703 (2018)

### ISSUE THREAD

**Issue by Staubgeborener** [suborb/philips_android_tv#23]
I'll get an error while trying to pair my 50PUS6703 (2018), because of exceeding max of retries.

```
python2 ./philips.py --host 192.168.178.XX pair
Starting pairing request
Traceback (most recent call last):
  File "./philips.py", line 123, in <module>
    main()
  File "./philips.py", line 90, in main
    pair(config)
  File "./philips.py", line 41, in pair
    r = requests.post("https://" + config['address'] + ":1926/6/pair/request", json=data, verify=False)
  File "C:\Python27\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.178.XX', port=1926): Max retries exceeded with url: /6/pair/request (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000040535C8>: Failed to establish a new connection: [Errno 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
```

Yes, the IP is correct and i can connect to http://192.168.178.XX:1925/1/system and see some stuff of the API 6.1. But i am also **not** able to connect to http://192.168.178.XX:1926/6/pair/request.

**Comment by Staubgeborener** [comment]
The problem appears to be local. The API was often completely unreachable and the TV had to be restarted a couple of times. My TV doesn't seem to use jointspace (no username / password authentication either?), although the model range should do that. Furthermore there were often connection problems (picture and sound is intermittently disturbed eg if the API was used together with Homebridge). All in all, this can be concluded here.
