### ISSUE TITLE
Not Working on 55OLED854

### ISSUE THREAD

**Issue by Francis2b** [suborb/philips_android_tv#25]
I have a new Philips 55OLED854 and I can't pair my TV here is the log:

> xxxxxxxx@raspberrypi:~/philips_android_tv $ python ./philips.py --host 192.168.1.37 pair
> Starting pairing request
> Traceback (most recent call last):
>   File "./philips.py", line 123, in <module>
>     main()
>   File "./philips.py", line 90, in main
>     pair(config)
>   File "./philips.py", line 41, in pair
>     r = requests.post("https://" + config['address'] + ":1926/6/pair/request", json=data, verify=False)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.1.37', port=1926): Max retries exceeded with url: /6/pair/request (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75ed2e90>: Failed to establish a new connection: [Errno 111] Connection refused',))

Thanks for your help

**Comment by Francis2b** [comment]
Problem solved!

Before starting the script on yout TV go to:
All Settings->Wireless an network-> Remote Control-> Pair remote control 

;-)
