### ISSUE TITLE
issue with Paring 58PUS7304 (2019)

### ISSUE THREAD

**Issue by woots82** [suborb/philips_android_tv#26]
python script fails at:

Starting pairing request
Traceback (most recent call last):
  File "./python.py", line 123, in <module>
    main()
  File "./python.py", line 90, in main
    pair(config)
  File "./python.py", line 41, in pair
    r = requests.post("https://" + config['address'] + ":1926/6/pair/request", json=data, verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

Im using HOOBS v3.1.23 and this plugin https://www.npmjs.com/package/homebridge-philipstelevision-v.1.2

Please take a look at it, I was already on support with the HOOBS Guys @BobbySlope

**Comment by suborb** [comment]
I think that's a Saphi based model? In which case I think this program isn't needed: there's just a set of hardcoded credentials that are needed.

Take a look at here: https://github.com/suborb/philips_android_tv/issues/22#issuecomment-633297190 and add the Authorization header to your webcall. Hopefully that will work.
