### ISSUE TITLE
i have error

### ISSUE THREAD

**Issue by d4nm0** [suborb/philips_android_tv#38]
hello i write and return error

```
python3 philips.py --host 192.168.1.228 pair
Starting pairing request
Traceback (most recent call last):
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 140, in _new_conn
    conn = connection.create_connection(
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 149, in _new_conn
    raise NewConnectionError(
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b80854130>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 413, in send
    resp = conn.urlopen(
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 648, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.228', port=1926): Max retries exceeded with url: /6/pair/request (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b80854130>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "philips.py", line 140, in <module>
    main()
  File "philips.py", line 90, in main
    pair(config)
  File "philips.py", line 41, in pair
    r = requests.post("https://" + config['address'] + ":1926/6/pair/request", json=data, verify=False)
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/danmonceau/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.1.228', port=1926): Max retries exceeded with url: /6/pair/request (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b80854130>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by suborb** [comment]
The key thing here is; "Connection refused"

Are you sure it's an Android TV? If it's a Saphi one, then this utility isn't needed and you should read here: https://github.com/suborb/philips_android_tv/issues/22#issuecomment-633297190

**Comment by d4nm0** [comment]
PHILIPS - TV LED 4K 55" 138 cm - 55PUS7805/12 Ambilight ?

**Comment by suborb** [comment]
Yup, that's a Saphi model, not an Android one: https://www.download.p4c.philips.com/files/5/55pus7805_12/55pus7805_12_dfu_eng.pdf

**Comment by d4nm0** [comment]
there has been no change :(

**Comment by Andi51081** [comment]
I have this same issue on my new 55PUS7956/12 but it has Android TV so surely isn’t Saphi?

**Comment by d4nm0** [comment]
i think android is not saphi

**Comment by slacky84** [comment]
did anyone get this working? I have an Android OLED TV and get the same issue.
