### ISSUE TITLE
Collections has no attribute error

### ISSUE THREAD

**Issue by eldudemeister** [suborb/philips_android_tv#47]
Hi, trying to run the script and I get the below error? 
```
Traceback (most recent call last):
  File "/home/matt/philips_android_tv/philips.py", line 6, in <module>
    import requests
  File "/home/matt/.local/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/home/matt/.local/lib/python3.10/site-packages/requests/utils.py", line 29, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/matt/.local/lib/python3.10/site-packages/requests/cookies.py", line 174, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
I'm running the command python3 philips.py --host [IP] pair

Any help would be appreciated?

**Comment by eldudemeister** [comment]
Sorted by running as sudo….
